name: "Continuous Integration"

on:
  push:
    # nb: no pr-branch below!
    branches: [main, sample-branch]
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - run: echo 'running on pr-from-other-org with ${{ steps.extract_branch.outputs.branch }}'
