name: "Continuous Integration"

on:
  push:
    branches: [main]
  pull_request:
  schedule:
    - cron: "0 1 * * *"

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - run: echo 'running on main with ${{ steps.extract_branch.outputs.branch }}'
