name: "Release"

run-name: > 
  Release of ${{ github.event.workflow_run.head_branch }} 
  at ${{ github.event.workflow_run.head_commit.id }} 
  from ${{ github.event.workflow_run.head_repository.full_name }} 
  by ${{ github.actor.login }}

on:
  workflow_run:
    workflows: [Continuous Integration]
    types: [completed]
#    branches: [main]

jobs:
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'Continuous Integration failed, not releasing...'

  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: "echo 'The triggering workflow passed: ${{ toJson(github.event.workflow_run) }}'"

  show-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: '${{ github.event.workflow_run.head_repository.full_name }}'
          ref: ${{ github.event.workflow_run.head_branch }}
      - run: git branch
      - run: env
      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - run: echo 'running on pr-from-other-org with ${{ steps.extract_branch.outputs.branch }}'
